<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RepseCatalogSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $catalogs = [
            ['clavepProdServ' => '90101604', 'descripcion' => 'Servicios de cáterin en la obra o lugar de trabajo', 'status' => true],
            ['clavepProdServ' => '76111500', 'descripcion' => 'Servicios de limpieza y mantenimiento de edificios generales y de oficinas', 'status' => true],
            ['clavepProdServ' => '76122405', 'descripcion' => 'Tarifa de mano de obra', 'status' => true],
            ['clavepProdServ' => '85121501', 'descripcion' => 'Servicios de atención domiciliaria por médicos de atención primaria', 'status' => true],
            ['clavepProdServ' => '72101507', 'descripcion' => 'Servicio de mantenimiento de edificios', 'status' => true],
            ['clavepProdServ' => '72102900', 'descripcion' => 'Servicios de mantenimiento y reparación de instalaciones', 'status' => true],
            ['clavepProdServ' => '81101513', 'descripcion' => 'Gestión de construcción de edificios', 'status' => true],
            ['clavepProdServ' => '72153900', 'descripcion' => 'Servicio de preparación de obras de construcción', 'status' => true],
            ['clavepProdServ' => '72121500', 'descripcion' => 'Servicios de construcción de plantas industriales', 'status' => true],
            ['clavepProdServ' => '92121504', 'descripcion' => 'Servicios de guardas de seguridad', 'status' => true],
            ['clavepProdServ' => '80101500', 'descripcion' => 'Servicios de consultoría de negocios y administración corporativa', 'status' => true],
            ['clavepProdServ' => '73121610', 'descripcion' => 'Servicios de herrería', 'status' => true],
            ['clavepProdServ' => '46171610', 'descripcion' => 'Cámaras de seguridad', 'status' => true],
            ['clavepProdServ' => '72101511', 'descripcion' => 'Servicio de instalación o mantenimiento o reparación de aires acondicionados', 'status' => true],
            ['clavepProdServ' => '72121000', 'descripcion' => 'Servicios de construcción de edificios industriales y bodegas nuevas', 'status' => true],
            ['clavepProdServ' => '40101800', 'descripcion' => 'Equipo de calefacción y piezas y accesorios', 'status' => true],
            ['clavepProdServ' => '84111506', 'descripcion' => 'Servicios de facturación', 'status' => true],
            ['clavepProdServ' => '73121602', 'descripcion' => 'Servicios de herrería', 'status' => true],
            ['clavepProdServ' => '39121002', 'descripcion' => 'Transformadores de suministro de potencia', 'status' => true],
            ['clavepProdServ' => '85101601', 'descripcion' => 'Servicios de enfermería', 'status' => true],
            ['clavepProdServ' => '70171802', 'descripcion' => 'Drenaje de agua pluviales', 'status' => true],
            ['clavepProdServ' => '85121800', 'descripcion' => 'Laboratorios médicos', 'status' => true],
            ['clavepProdServ' => '25101703', 'descripcion' => 'Ambulancias', 'status' => true],
            ['clavepProdServ' => '72151001', 'descripcion' => 'Servicio de mantenimiento de calderas', 'status' => true],
            ['clavepProdServ' => '91111603', 'descripcion' => 'Servicios de cocina o preparación de comidas', 'status' => true],
            ['clavepProdServ' => '72151605', 'descripcion' => 'Servicio de cableado para video, datos y voz', 'status' => true],
            ['clavepProdServ' => '23152200', 'descripcion' => 'Mesa y estantes para fabricación', 'status' => true],
            ['clavepProdServ' => '85121502', 'descripcion' => 'Servicios de consulta de médicos de atención primaria', 'status' => true],
            ['clavepProdServ' => '71121000', 'descripcion' => 'Servicios de bombear cemento', 'status' => true],
            ['clavepProdServ' => '90101500', 'descripcion' => 'Establecimientos para comer y beber', 'status' => true],
            ['clavepProdServ' => '43222610', 'descripcion' => 'Concentradores o hubs de servicio de red', 'status' => true],
            ['clavepProdServ' => '92101902', 'descripcion' => 'Servicios de ambulancia', 'status' => true],
            ['clavepProdServ' => '40101600', 'descripcion' => 'Circulación del aire y piezas y accesorios', 'status' => true],
            ['clavepProdServ' => '72101500', 'descripcion' => 'Servicios de apoyo para la construcción', 'status' => true],
            ['clavepProdServ' => '72141700', 'descripcion' => 'Servicios de alquiler o arrendamiento de equipo y maquinaria de construcción', 'status' => true],
            ['clavepProdServ' => '72151500', 'descripcion' => 'Servicios de sistemas eléctricos', 'status' => true],
            ['clavepProdServ' => '13111000', 'descripcion' => 'Resinas', 'status' => true],
            ['clavepProdServ' => '15121804', 'descripcion' => 'Preparación contra óxido', 'status' => true],
            ['clavepProdServ' => '72153608', 'descripcion' => 'Servicio de instalación de cortinas o persianas', 'status' => true],
            ['clavepProdServ' => '72152600', 'descripcion' => 'Servicios de techado y paredes externas y láminas de metal', 'status' => true],
            ['clavepProdServ' => '72151204', 'descripcion' => 'Servicio de trabajo de ductos y ventilación hvac', 'status' => true],
            ['clavepProdServ' => '40142000', 'descripcion' => 'Mangueras', 'status' => true],
            ['clavepProdServ' => '90101700', 'descripcion' => 'Servicios de cafetería', 'status' => true],
            ['clavepProdServ' => '78111802', 'descripcion' => 'Servicios de buses con horarios programados', 'status' => true],
            ['clavepProdServ' => '80111701', 'descripcion' => 'Servicios de contratación de personal', 'status' => true],
            ['clavepProdServ' => '40161508', 'descripcion' => 'Filtros de bolsa', 'status' => true],
            ['clavepProdServ' => '41116146', 'descripcion' => 'Kits o suministros para pruebas de toxicología', 'status' => true],
            ['clavepProdServ' => '78111803', 'descripcion' => 'Servicios de buses contratados', 'status' => true],
            ['clavepProdServ' => '76111600', 'descripcion' => 'Servicios de limpieza de componentes de edificios', 'status' => true],
            ['clavepProdServ' => '80111600', 'descripcion' => 'Servicios de personal temporal', 'status' => true],
            ['clavepProdServ' => '72154003', 'descripcion' => 'Servicio de instalación de toldos', 'status' => true],
            ['clavepProdServ' => '51142100', 'descripcion' => 'Fármacos antiinflamatorios no esteroideos (NSAID)', 'status' => true],
            ['clavepProdServ' => '76111501', 'descripcion' => 'Servicios de limpieza de edificios', 'status' => true],
            ['clavepProdServ' => '72101509', 'descripcion' => 'Servicio de mantenimiento o reparación de equipos y sistemas de protección contra incendios', 'status' => true],
            ['clavepProdServ' => '80111618', 'descripcion' => 'Servicios temporales de construcción', 'status' => true],
            ['clavepProdServ' => '11111502', 'descripcion' => 'Material de relleno', 'status' => true],
            ['clavepProdServ' => '42295100', 'descripcion' => 'Equipo quirúrgico y accesorios y productos relacionados', 'status' => true],
            ['clavepProdServ' => '41115827', 'descripcion' => 'Analizadores de orina', 'status' => true],
            ['clavepProdServ' => '41111953', 'descripcion' => 'Sensor de armado de inflador de restricción (bolsa de aire) suplementario', 'status' => true],
            ['clavepProdServ' => '41104100', 'descripcion' => 'Contenedores de recogida y transporte de especímenes, y suministros', 'status' => true],
            ['clavepProdServ' => '72102902', 'descripcion' => 'Servicios de paisajismo', 'status' => true],
            ['clavepProdServ' => '40171500', 'descripcion' => 'Tubos y tuberías comerciales', 'status' => true],
            ['clavepProdServ' => '39121700', 'descripcion' => 'Ferretería eléctrica y suministros', 'status' => true],
            ['clavepProdServ' => '72154503', 'descripcion' => 'Servicio de alquiler de grúas', 'status' => true],
            ['clavepProdServ' => '30171613', 'descripcion' => 'Paredes de vidrio', 'status' => true],
            ['clavepProdServ' => '72154059', 'descripcion' => 'Servicios de detección, sellado y reparación de fugas', 'status' => true],
            ['clavepProdServ' => '52131501', 'descripcion' => 'Cortinas', 'status' => true],
            ['clavepProdServ' => '27112802', 'descripcion' => 'Hojas de sierra', 'status' => true],
            ['clavepProdServ' => '30151703', 'descripcion' => 'Canaletas', 'status' => true],
            ['clavepProdServ' => '72152900', 'descripcion' => 'Servicios de montaje de acero estructural', 'status' => true],
            ['clavepProdServ' => '85122200', 'descripcion' => 'Servicios de evaluación y valoración de salud individual', 'status' => true],
            ['clavepProdServ' => '72152400', 'descripcion' => 'Servicios de montaje e instalación de ventanas y puertas', 'status' => true],
            ['clavepProdServ' => '73152100', 'descripcion' => 'Servicios de mantenimiento y reparación de equipo de manufactura', 'status' => true],
            ['clavepProdServ' => '41103007', 'descripcion' => 'Unidades de enfriamiento o circuladores de agua fría', 'status' => true],
            ['clavepProdServ' => '73152101', 'descripcion' => 'Servicio de mantenimiento de equipo industrial', 'status' => true],
            ['clavepProdServ' => '73152102', 'descripcion' => 'Servicio de reparación de equipo industrial', 'status' => true],
            ['clavepProdServ' => '24101600', 'descripcion' => 'Equipo de izaje y accesorios', 'status' => true],
            ['clavepProdServ' => '41112403', 'descripcion' => 'Indicadores de presión', 'status' => true],
            ['clavepProdServ' => '41112205', 'descripcion' => 'Reguladores de temperatura', 'status' => true],
            ['clavepProdServ' => '40101701', 'descripcion' => 'Aires acondicionados', 'status' => true],
            ['clavepProdServ' => '81101500', 'descripcion' => 'Ingeniería civil', 'status' => true],
            ['clavepProdServ' => '41112209', 'descripcion' => 'Termostatos', 'status' => true],
            ['clavepProdServ' => '30171500', 'descripcion' => 'Puertas', 'status' => true],
            ['clavepProdServ' => '30266501', 'descripcion' => 'Banda de caucho', 'status' => true],
            ['clavepProdServ' => '72152300', 'descripcion' => 'Servicios de carpintería', 'status' => true],
            ['clavepProdServ' => '30171614', 'descripcion' => 'Pantallas de ventana', 'status' => true],
            ['clavepProdServ' => '81141500', 'descripcion' => 'Control de calidad', 'status' => true],
            ['clavepProdServ' => '85122201', 'descripcion' => 'Valoración del estado de salud individual', 'status' => true],
            ['clavepProdServ' => '72151207', 'descripcion' => 'Servicio de instalación y mantenimiento acondicionamiento del aire, enfriamiento y calefacción hvac', 'status' => true],
            ['clavepProdServ' => '27112800', 'descripcion' => 'Conexiones de herramientas y accesorios', 'status' => true],
            ['clavepProdServ' => '72102100', 'descripcion' => 'Control de plagas', 'status' => true],
            ['clavepProdServ' => '81101605', 'descripcion' => 'Servicios electromecánicos', 'status' => true],
            ['clavepProdServ' => '81101701', 'descripcion' => 'Servicios de ingeniería eléctrica', 'status' => true],
        ];

        DB::table('repse_catalogs')->insert($catalogs);
    }
}